//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppointment
    {
        public int AppointmentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Duration { get; set; }
        public string Pending { get; set; }
        public string Confirmed { get; set; }
        public string Cancelled { get; set; }
        public Nullable<int> PaymentID { get; set; }
    
        public virtual tblPayment tblPayment { get; set; }
    }
}
