//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        public tblAdmin()
        {
            this.tblSchedules = new HashSet<tblSchedule>();
        }
    
        public int AdminID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual tblRole tblRole { get; set; }
        public virtual ICollection<tblSchedule> tblSchedules { get; set; }
    }
}
