//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Appointment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public tblRole()
        {
            this.tblAdmins = new HashSet<tblAdmin>();
        }
    
        public int RoleID { get; set; }
        public string Name { get; set; }
        public string CanCreate { get; set; }
        public string CanRead { get; set; }
        public string CanUpdate { get; set; }
        public string CanDelete { get; set; }
        public string Receptionist { get; set; }
        public string Doctor { get; set; }
    
        public virtual ICollection<tblAdmin> tblAdmins { get; set; }
    }
}
